### ISSUE TITLE
Some unresolved issues

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#53]
Similarly to https://github.com/flutter-tizen/flutter-tizen/issues/60, here are some works to be done for the engine and our embedder. Please open a dedicated issue or PR if you are interested with any.

- [x] Alternative logging method on TVs (avoid using `__dlog_print`) → #67
- [x] Advanced continuous integration  → Addressed by #89
- [x] Non-fatal error "xkbcommon: ERROR: couldn't find a Compose file for locale" on app launch (unrelated to Flutter)  → #91
- [x] Endless thread creation on watch devices ("Thread added to display, Thread removed to display, ...")  → Not reproducible
- [x] Implement platform channel methods (`setPreferredOrientations`, `vibrate`, `Clipboard.*`, `play`)  → #65, #75, #79, #84
- [ ] Analyze performance issues (gallery app is sluggish, frame janks)
- [x] Investigate why SkSL shaders cannot be collected on Tizen devices  → #55
- [x] Symbol resolution fails for system libraries in DevTools stack traces  → #95
- [x] Cupertino widget animation flickering issue on TM1 devices → #130
- [x] Enable arm64 engine builds  → #63
- [x] Remove Tizen-specific texture APIs  → #82
- [x] Overall refactoring → WIP

**Comment by bbrto21** [comment]
I checked about Endless thread creation, but I didn't see that case. Could you tell me how to reproduce it?
As a result of my checking, whether it is a flutter app or just an app, thread creation and deletion occurs several times.

**Comment by swift-kim** [comment]
@bbrto21 It occurs on my Galaxy Watch (R805) device usually after a long time from booting. I said it's "endless" because a thread is created and deleted repeatedly on every touch event (up, down, move). The same bug has previously been reported and fixed by #32 but it still occurs on my device occasionally. I'll show you when I manage to reproduce it.

**Comment by bbrto21** [comment]
> - Cupertino widget animation flickering issue on TM1 devices

I don't know what this means, somehow, it didn't occur with Evas GL.
But it happens in Evas GL direct mode, which may be because our PoC implementation is not perfect.
I'm not sure, but I leave this comment as it seems to be useful.

**Comment by swift-kim** [comment]
@bbrto21 When you start the Gallery app on a TM1 device (not emulator but real device) and open one of Cupertino widget examples, you will get what the problem is. I reported this issue for the first time in M Chat about months ago. It could be an issue with ecore_wl so it may not happen with the Evas GL backend.

**Comment by bbrto21** [comment]
> @bbrto21 When you start the Gallery app on a TM1 device (not emulator but real device) and open one of Cupertino widget examples, you will get what the problem is. I reported this issue for the first time in M Chat about months ago. It could be an issue with ecore_wl so it may not happen with the Evas GL backend.

There seems to be some misunderstanding. I know that there is a problem with ecore_wl. What I'm trying to share is that I don't know why, but the problem goes away in Evas GL. Thanks for your interest!

**Comment by XuWanchaoS** [comment]
=> Alternative logging method on TVs (avoid using __dlog_print)
Do you mean change '__dlog_print' to 'dlog_print' in tizen_log.h?

On TV 6.0 emulator, it should add '-b system' for dlogutil to print log when using __dlog_print, and add '-b apps' when using 'dlog_print'.

**Comment by swift-kim** [comment]
Yes, I was working on a method that globally works on TV, watch, and emulators. (https://github.com/swift-kim/engine/commits/dlog-internal)

> On TV 6.0 test emulator, it should add '-b system' for dlogutil to print log when using __dlog_print, and add '-b apps' when using 'dlog_print'.

So this option can be enabled for test emulators only? I'll ask you how to get the test emulator personally later.

**Comment by pwasowski2** [comment]
> 
>     * Implement platform channel methods (`setPreferredOrientations`, `vibrate`, ~`Clipboard.*`~)
> 

I have implemented HapticFeedback.vibrate() in this PR: https://github.com/flutter-tizen/engine/pull/75

In `src/flutter/shell/platform/tizen/channels/platform_channels.cc`, there's also unimplemented `SystemSound.play`. Is it on our TODO list? If so, I can implement it ;)

**Comment by swift-kim** [comment]
@pwasowski2 I'm not sure how often `SystemSound.play` is used by normal apps but of course you can implement it if you want. :)

**Comment by pkosko** [comment]
I've marked this point as 'done'

> Implement platform channel methods (setPreferredOrientations, vibrate, Clipboard.*, play)

because of PRs:
* https://github.com/flutter-tizen/engine/pull/75
* https://github.com/flutter-tizen/engine/pull/76
* https://github.com/flutter-tizen/engine/pull/79
* https://github.com/flutter-tizen/engine/pull/84

**Comment by pwasowski2** [comment]
>     * Non-fatal error "xkbcommon: ERROR: couldn't find a Compose file for locale" on app launch (unrelated to Flutter)

@swift-kim, could you please tell how to reproduce the problem? I have launched the basic app, generated with `flutter-tizen create` on my TM1 device and haven't seen this error in `dlog` output. Have I been even looking in the right place? 😕

**Comment by bbrto21** [comment]
@pwasowski2
1. Launch Settings 
2. Go -  Language and input
3. Go - Display language
4. Choose a language other than English
5. Launch flutter-app

**Comment by bbrto21** [comment]
I guess it's a problem with the Compose file. Actually, TM1 only has compose file of en_US.UTF-8 as below.
I don't think this is a serious problem, but I don't know why this error log doesn't occur when launch other normal Tizen apps.

``` bash
sh-3.2# pwd
/usr/share/X11/locale
sh-3.2# ls
compose.dir  en_US.UTF-8  locale.alias
```

**Comment by pwasowski2** [comment]
@bbrto21, thanks for showing how to reproduce the problem 👍  I'll look into it. I have opened a new issue for it #91

**Comment by swift-kim** [comment]
> I don't know why this error log doesn't occur when launch other normal Tizen apps.

@bbrto21 The error occurs for non-Flutter apps as well. That's why I marked it "unrelated to Flutter".

**Comment by bbrto21** [comment]
@swift-kim, cc @pwasowski2 
Under the same conditions, when I launched a simple native app, I didn't see this log. 
How do I reproduce when I launch non-flutter apps?

**Comment by pwasowski2** [comment]
@swift-kim, @bbrto21, I have run a web and native app and the problem didn't show up, too.

**Comment by swift-kim** [comment]
I used to see the message when I was launching .NET apps but I'm not sure about the native apps.

**Comment by pwasowski2** [comment]
@swift-kim, could you please provide more info about this problem?

> Symbol resolution fails for system libraries in DevTools stack traces

I haven't yet experienced this problem - could you please tell how to reproduce it?

**Comment by swift-kim** [comment]
@pwasowski2 If you run an app in profile mode and open [the Performance view](https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/devtools-usage.md#performance-view) in Flutter DevTools, you will see this screen:

![Screenshot from 2021-05-25 10-04-42](https://user-images.githubusercontent.com/40190588/119424620-c6744f80-bd40-11eb-85e6-3b8dab34b2b5.png)

As you can see in the stack traces at the bottom of the view (CPU Flame Chart), symbols are resolved to their offsets within the shared objects (`/proc/self/fd/35/lib/libflutter_engine.so+0x.....`) but not their actual names. I'm not sure whether this is normal (because the symbols were stripped out).

**Comment by pwasowski2** [comment]
@swift-kim, thanks for the detailed description. I'll look into the problem in #95.
For now, I guess that we'll at most be able to show the symbol names if "debug" RPMs for the libraries are installed.

**Comment by swift-kim** [comment]
> Cupertino widget animation flickering issue on TM1 devices

This issue now occurs on watch devices too. We need to check why.

**Comment by swift-kim** [comment]
Every issue has been addressed by a separate issue or PR. Closing.
